[JX_Wiki]
name=资料库
desc=流程攻略、任务查询、美人图、门派技能手册
version=1.0
default=1
package=JX
lua_0=JX_Wiki.lua
lua_1=QuestState.lua
#lua_4=JX_Achievement.lua
lua_2=JX_MeiRenTu.lua
lua_3=JX_AllForceSkill.lua
lua_4=JX_ItemSearch.lua
